version: '3.8'

services:
  api:
    build: .
    container_name: banking_api_container
    ports:
      - "8000:8000"
    volumes:
      # PERSISTANCE DES DONNÉES :
      # On mappe un dossier local "kaggle_data" vers le cache interne du conteneur.
      # Ainsi, les CSV restent sur ton disque dur même si tu supprimes le conteneur.
      - ./kaggle_data:/root/.cache/kagglehub
    environment:
      - APP_ENV=production
    restart: unless-stopped